import image from '../../assets/image.png'
const productData = [
    {
      image:image,
      featured: false,
      price: 825000,
      year: 2016,
      kms: 85000,
      name: "Mahindra XUV500 2.2 W10",
      location: "Gujaral Nagar, Jalandhar",
      date: "Feb 02",
    },
    {
      image: 'https://apollo.olx.in/v1/files/3jxon4vdkcfp2-IN/image;s=300x600;q=60',
      featured: false,
      price: 750000,
      year: 2019,
      kms: 52230,
      name: "Nissan Kicks XL D",
      location: "Vasai Road, Mumbai",
      date: "Feb 12",
    },
    {
      image: "https://apollo.olx.in/v1/files/f2i5okx67gy6-ADVIN/image;s=300x600;q=60",
      featured: false,
      price: 36000,
      year: null,
      kms: null,
      name: "Samsung S23 Ultra (6 months old)",
      location: "Samudrapur, Maharashtra",
      date: "Yesterday",
    },
    {
      image:'https://apollo.olx.in/v1/files/cv292gruqihz-ADVIN/image;s=300x600;q=60',
      featured: false,
      price: 32499,
      year: null,
      kms: null,
      name: "iPhone 15 Holi Special",
      location: "Samudrapur, Maharashtra",
      date: "2 days ago",
    },
    {
      image: "https://apollo.olx.in/v1/files/7jfmkfn7wols2-ADVIN/image;s=300x600;q=60",
      featured: false,
      price: 380000,
      year: 2011,
      kms: 100000,
      name: "Mahindra Scorpio N Diesel",
      location: "Shahangadi, Hinganghat",
      date: "6 days ago",
    },
    {
      image: "https://apollo.olx.in/v1/files/dw9m2y0dl5y-IN/image;s=300x600;q=60",
      featured: false,
      price: 155000,
      year: 2012,
      kms: 101500,
      name: "Chevrolet Beat Diesel",
      location: "Maruti Ward, Hinganghat",
      date: "Feb 24",
    },
    {
      image: "https://apollo.olx.in/v1/files/bvu8kaa385n1-IN/image;s=300x600;q=60",
      featured: false,
      price: 12500000,
      year: null,
      kms: null,
      name: "4 Acre Agriculture Land",
      location: "Samudrapur, Maharashtra",
      date: "Feb 07",
    },
    {
      image: "https://apollo.olx.in/v1/files/d6g3hrw1fc4t1-ADVIN/image;s=300x600;q=60",
      featured: false,
      price: 999,
      year: null,
      kms: null,
      name: "Combo of 4 Check Shirts",
      location: "Samudrapur, Maharashtra",
      date: "Yesterday",
    },
    {
        image: 'https://apollo.olx.in/v1/files/kg1gmr0vsitu-IN/image;s=300x600;q=60',
        featured: false,
        price: 2000,
        year: null,
        kms: null,
        name: "We have new latest collection ultra sim watches online order book",
        location: "Samudrapur, Maharashtra",
        date: "Aug 13",
      },
      {
        image: "https://apollo.olx.in/v1/files/ek46mldc973v-ADVIN/image;s=300x600;q=60",
        featured: false,
        price: 899,
        year: null,
        kms: null,
        name: "Men's Sneakers",
        location: "Samudrapur, Maharashtra",
        date: "4 days ago",
      },
      {
        image: "https://apollo.olx.in/v1/files/fl8tand0byst1-ADVIN/image;s=300x600;q=60",
        featured: false,
        price: 4000000,
        year: null,
        kms: null,
        name: "House for sale",
        location: "Hinganghat MIDC, Maharashtra",
        date: "Feb 24",
      },
      {
        image: "https://apollo.olx.in/v1/files/9oxf0vqkq9fw2-IN/image;s=300x600;q=60",
        featured: false,
        price: 900,
        year: null,
        kms: null,
        name: "NEW (PACK OF 3) CHEX CHECKERD SHIRT HOME DELIVERY ALL INDIA COD YES",
        location: "Samudrapur, Maharashtra",
        date: "4 days ago",
      },
      {
        image: "https://apollo.olx.in/v1/files/qyvpg6e32bcm2-ADVIN/image;s=300x600;q=60",
        featured: false,
        price: 700,
        year: null,
        kms: null,
        name: "Krishna ji Murti",
        location: "Samudrapur, Maharashtra",
        date: "Feb 24",
      },
      {
        image: "https://apollo.olx.in/v1/files/9bjnslvfvne22-ADVIN/image;s=300x600;q=60",
        featured: false,
        price: 1800,
        year: null,
        kms: null,
        name: "NEW OFFER (COMBO PACK OF 5) SILK SAREE HOME DELIVERY ALL INDIA COD YES",
        location: "Samudrapur, Maharashtra",
        date: "5 days ago",
      },
      {
        image: "https://apollo.olx.in/v1/files/j3z76kvhodf2-IN/image;s=300x600;q=60",
        featured: false,
        price: 180000,
        year: null,
        kms: null,
        name: "Library | Call Center | Office Setup | Free Delivery",
        location: "Samudrapur, Maharashtra",
        date: "Feb 18",
      },
      {
        image: "https://apollo.olx.in/v1/files/6pshadwjvw9p2-IN/image;s=300x600;q=60",
        featured: false,
        price: 429,
        year: null,
        kms: null,
        name: "Nova hair dryer",
        location: "Samudrapur, Maharashtra",
        date: "Feb 20",
      },
      {
        image: "https://apollo.olx.in/v1/files/sxhocmyft86u1-ADVIN/image;s=300x600;q=60",
        featured: false,
        price: 5000,
        year: null,
        kms: null,
        name: "iphonne 13 care housing made in usa",
        location: "Samudrapur, Maharashtra",
        date: "6 days ago",
      },
      {
        image: "https://apollo.olx.in/v1/files/bj8iuvjun12d1-IN/image;s=300x600;q=60",
        featured: false,
        price: 349,
        year: null,
        kms: null,
        name: "Attractive Black Suede Flat Sandals For Women | Home Delivery",
        location: "Samudrapur, Maharashtra",
        date: "Feb 17",
      },
      {
        image: "https://apollo.olx.in/v1/files/kuo2jiikh87c2-IN/image;s=300x600;q=60",
        featured: false,
        price: 450,
        year: null,
        kms: null,
        name: "Stainless steel bottle 1 litre and foldable bootle with 0.5 ml",
        location: "Samudrapur, Maharashtra",
        date: "Feb 21",
      },
      {
        image: "https://apollo.olx.in/v1/files/ik8p3c436wks1-IN/image;s=300x600;q=60",
        featured: false,
        price: 299,
        year: null,
        kms: null,
        name: "Trending Sports Watch For Men/Boys",
        location: "Samudrapur, Maharashtra",
        date: "Feb 15",
      },
    //   {
    //     image: "https://apollo.olx.in/v1/files/laptop1-IN/image;s=300x600;q=60",
    //     featured: false,
    //     price: 35000,
    //     year: null,
    //     kms: null,
    //     name: "Dell Inspiron 15 - 8GB RAM - 512GB SSD - Like New",
    //     location: "Hinganghat, Maharashtra",
    //     date: "Yesterday",
    //   },
    //   {
    //     image: "https://apollo.olx.in/v1/files/shirt2-IN/image;s=300x600;q=60",
    //     featured: true,
    //     price: 999,
    //     year: null,
    //     kms: null,
    //     name: "Combo of 4 Check Shirts",
    //     location: "Samudrapur, Maharashtra",
    //     date: "Yesterday",
    //   },
    //   {
    //     image: "https://apollo.olx.in/v1/files/sofa1-IN/image;s=300x600;q=60",
    //     featured: false,
    //     price: 28500,
    //     year: null,
    //     kms: null,
    //     name: "5 Seater L-Shape Sofa Set with Premium Fabric - Home Delivery",
    //     location: "Warora, Maharashtra",
    //     date: "Feb 23",
    //   },
    //   {
    //     image: "https://apollo.olx.in/v1/files/camera1-IN/image;s=300x600;q=60",
    //     featured: false,
    //     price: 42000,
    //     year: null,
    //     kms: null,
    //     name: "Canon 200D DSLR with 18-55mm Lens Kit - Barely Used",
    //     location: "Chandrapur, Maharashtra",
    //     date: "Today",
    //   },
    //   {
    //     image: "https://apollo.olx.in/v1/files/airpods1-IN/image;s=300x600;q=60",
    //     featured: false,
    //     price: 3499,
    //     year: null,
    //     kms: null,
    //     name: "Apple Airpods Pro Clone - Premium Quality with Noise Cancellation",
    //     location: "Samudrapur, Maharashtra",
    //     date: "2 days ago",
    //   },
    //   {
    //     image: "https://apollo.olx.in/v1/files/tshirt1-IN/image;s=300x600;q=60",
    //     featured: false,
    //     price: 499,
    //     year: null,
    //     kms: null,
    //     name: "Pack of 3 Premium Cotton T-shirts - Free Shipping",
    //     location: "Chandrapur, Maharashtra",
    //     date: "Today",
    //   },
    //   {
    //     image: "https://apollo.olx.in/v1/files/microwave1-IN/image;s=300x600;q=60",
    //     featured: false,
    //     price: 4500,
    //     year: null,
    //     kms: null,
    //     name: "Samsung 20L Solo Microwave Oven - 1 Year Old",
    //     location: "Warora, Maharashtra",
    //     date: "3 days ago",
    //   },
    //   {
    //     image: "https://apollo.olx.in/v1/files/bag1-IN/image;s=300x600;q=60",
    //     featured: true,
    //     price: 799,
    //     year: null,
    //     kms: null,
    //     name: "Ladies Stylish Handbag - Brand New - COD Available",
    //     location: "Samudrapur, Maharashtra",
    //     date: "Yesterday",
    //   }
  ];
  
  export default productData;
  